modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="mechina_addon"
version="1.0.01"
displayName="Mechina add-on"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="US"

[[dependencies.mechina_addon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




